apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-xfers-io-xfers-rails-app-core-tiny-rollbar
  labels:
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: xfers-tiny-rollbar
    tags.datadoghq.com/country: SG
    tags.datadoghq.com/version: 2022-06-28-latest
    app.kubernetes.io/name: xfers-rails-app-core-tiny-rollbar
    helm.sh/chart: xfers-rails-app-core-0.6.1
    app.kubernetes.io/instance: www-xfers-io
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 40%
  selector:
    matchLabels:
      app.kubernetes.io/name: xfers-rails-app-core-tiny-rollbar
      app.kubernetes.io/instance: www-xfers-io
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: production
        tags.datadoghq.com/service: xfers-tiny-rollbar
        tags.datadoghq.com/country: SG
        tags.datadoghq.com/version: 2022-06-28-latest
        app.kubernetes.io/name: xfers-rails-app-core-tiny-rollbar
        app.kubernetes.io/instance: www-xfers-io
      annotations:
        rollme: "RTBc5"
    spec:
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: xfers-rails-app-core
          image: "tim37021/tiny-rollbar-worker:v1.2.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: redis
          ports:
            - name: liveness-probe
              containerPort: 7433
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: [ "scripts/shutdown_sidekiq.sh" ]
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 1000Mi
        - name: redis
          image: "redis:7.0.2-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: p1
              containerPort: 6379
              protocol: TCP
